### ISSUE TITLE
Notify users on CLA error

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#12]
Right now we set the commit status and apply labels after auditing a PR, but neither of these will actually notify the contributor if there is a problem. We need to figure out how we want to notify contributors: via a PR comment or via an email.

**Comment by jzaefferer** [comment]
Travis sends emails, Angular/Google is using comments, [their format](https://github.com/angular/angular.js/pull/11014#issuecomment-73547700) looks like a good reference. They also [add another comment](https://github.com/angular/angular.js/pull/11006#issuecomment-73380001) when the CLA was signed.

**Comment by arschmitz** [comment]
A comment seems like a good way to go it sends an email to the contributor but its from Github not us which seems like a good thing.

**Comment by jzaefferer** [comment]
Having @jquerybot add a comment seems like a good idea, and should be pretty simple to implement.

**Comment by jzaefferer** [comment]
Something like this:

```md
Thank you for your pull request. It looks like this may be your first contribution to a jQuery Foundation project, so we need you to sign our Contributor License Agreement (CLA) at http://contribute.jquery.org/CLA/.

If you've already signed our CLA, it's possible your git author information doesn't match your CLA signature (both name and email have to match), for more information, [check the status of your CLA check](http://contribute.jquery.org/CLA/status/?repo=REPO&sha=SHA).

After you signed (again), the PR is checked again automatically. If there's still an issue, please reply here to let us know.
```

**Comment by arschmitz** [comment]
:+1:

**Comment by jzaefferer** [comment]
A more recent googlebot response:

![...](http://bassistance.de/i/0e414c.png)

Will see about integrating some of the changes into my draft.

**Comment by jzaefferer** [comment]
Updated comment template:

> Thank you for your pull request. It looks like this may be your first contribution to a jQuery Foundation project, if so we need you to sign our Contributor License Agreement (CLA).

> __Please visit http://contribute.jquery.org/CLA/ to sign.__

> After you signed, the PR is checked again automatically after a minute. If there's still an issue, please reply here to let us know.

> ---

> If you've already signed our CLA, it's possible your git author information doesn't match your CLA signature (both your name and email have to match), for more information, [check the status of your CLA check](http://contribute.jquery.org/CLA/status/?repo=REPO&sha=SHA).

**Comment by jzaefferer** [comment]
To avoid spamming comments, I think we can keep track of event.payload.action, and only post a comment when the check failed and the action is `event.payload.action === "opened"`.

Not sure yet where to actually implement this, since there are multiple locations where `repo.setStatus` is called. Hooking into that method would give us a single location, but seems like the wrong place.

**Comment by scottgonzalez** [comment]
> Not sure yet where to actually implement this, since there are multiple locations where repo.setStatus is called. Hooking into that method would give us a single location, but seems like the wrong place.

There are multiple calls, but only one call that you care about: the one in `finishAudit()`.
