### ISSUE TITLE
Better error reporting for invalid signatures

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#17]
Invalid CLA signatures are detected, but essentially thrown away. Now that audit results are shown, along with instructions on how to fix the problem, we should retain the information to provide better data on the details page.

https://github.com/jquery/jquery-ui/pull/1451 shows an example of this. Though, interestingly, the CLA was first signed correctly, then signed incorrectly to match the git config. So in this case, the current instructions were correct.

**Comment by jzaefferer** [comment]
Notes after reviewing with Scott: Keep the information about invalid signatures instead of throwing it out. May need to remove the duplicate email check.
