### ISSUE TITLE
Ability to recheck a PR

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#2]
Once #1 is implemented, it should be possible to click a button to recheck the PR. This will be useful for the scenario where a contributor signs the CLA after the check has failed.

**Comment by jzaefferer** [comment]
#1 is implemented, this is still useful. Maybe you could walk me through the necessary changes, so that I get a chance to implement this, without having to start from zero?

**Comment by dmethvin** [comment]
This is definitely a pain point for new contributors who are frequently confused by the process, so anything we can do to improve this would be great.

**Comment by jzaefferer** [comment]
If this is okay for everyone to trigger, it should just be a button on the contribute page that calls the audit-pr script.

**Comment by arschmitz** [comment]
Now that the signatures are re-checked every 60 seconds i don't think we need this any more. Maybe just add some wording to the failure page that it is re-checked every 60 seconds?

**Comment by jzaefferer** [comment]
We've checked a bunch of duplicate signatures. The interval is either so short that they would never notice a status change (double submit?) or, in most cases they waited at least several minutes before trying to submit the same signature again. The change from #6 therefore should make this irrelevant.
