### ISSUE TITLE
Output files are not being written in production

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#20]
This was working fine before. No errors are being reported when it doesn't work. When manually running with debug enabled, the files are being written just fine. @gnarf and I have no idea why this isn't working.

**Comment by jzaefferer** [comment]
Is the manual run using a different user?

**Comment by scottgonzalez** [comment]
Nope. Also even when the output files aren't written, the git repos are updated. Permissions and owners are the same for both directories.

**Comment by gnarf** [comment]
Is it maybe a path.resolve problem? Cwd?
