### ISSUE TITLE
Recover from broken clones

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#21]
If the process is killed in the middle of a clone, the repo will be left in a broken state. Since our repo detection is as simple as whether or not the directory exists, there's no recovery path from a broken repo. We can easily recover manually by just deleting the repo, but the script should be able to detect this and recover automatically.

**Comment by jzaefferer** [comment]
I guess running `git status` and looking at the exit code should do it.

**Comment by jzaefferer** [comment]
I don't think this is worth addressing until it actually happens. The potential risk is pretty low, since we end up with failing CLA checks, nothing more.
