### ISSUE TITLE
GitHub seems to be sending webhooks earlier than expected

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#23]
We've had a few errors today where the PR branch doesn't exist when the webhook is received.

```
Error: Command failed: fatal: Couldn't find remote ref refs/pull/1459/head
```

I haven't seen this happen before today. Off the top of my head, I can think of two workarounds:
* Introduce an arbitrary delay before processing the hook.
* Implement delayed retries on our requests.

I'd prefer the delayed retries. We can wrap all requests in the same logic for some extra robustness.

**Comment by arschmitz** [comment]
The delayed retries seems like a much better solution. Wrapping and re-trying all the requests will guard against any github api outages too.

**Comment by gnarf** [comment]
Delay retry - perhaps do a 10 second retry 5 times?

**Comment by scottgonzalez** [comment]
@gnarf I put together an implementation before I saw your comment about 5x 10s retries. We can certainly change the duration and number of attempts to whatever we want. I'll wait for more feedback in the PR.

**Comment by scottgonzalez** [comment]
Graceful retries aren't enough. https://github.com/jquery/jquery/pull/2043#issuecomment-76878343 shows a case where the PR was updated, then the check failed with a bad revision range. This happens because the PR branch already existed, then a new commit was pushed, and we fetched the PR branch before it was updated. We'll need to do retries on fetching the branches after an invalid range as well. This might get pretty complicated.

**Comment by gnarf** [comment]
Can we just compare it to the ref that we fetched?

**Comment by gnarf** [comment]
Oh man.... I see the problem now... Will sleep on it

**Comment by gnarf** [comment]
So I think the new process requires that each repo keep track of each "audit" it is currently running.

Edges that need solving and potential solutions

* [ ] Hook sent before ref exists - fetch fails, retry
* [ ] Hook sent before ref is updated to new sha - fetch succeeds, but log will fail from invalid refs
* [ ] Another hook is sent before the previous check passes or fails (because of retries / someone quickly pushing an ammended commit because the first one was messed up) - We should cancel the first audit and its retries and try to fetch using the new sha/ref.

One thought, could `git ls-remote origin refs/pull/77/head` help us know if the remote is pointed at the right ref yet before we fetch it?

**Comment by scottgonzalez** [comment]
> So I think the new process requires that each repo keep track of each "audit" it is currently running.

I'm not sure if we actually need to worry about that. The check is really fast and rapid successive updates to a PR aren't very common, so the chance that we'd double up on work is low. If we *do* double up on work, I'm not sure there's any potential problem with that.

>  Hook sent before ref exists - fetch fails, retry

Addressed in #24

>  Hook sent before ref is updated to new sha - fetch succeeds, but log will fail from invalid refs

Can't be determined until after we get an invalid range. At that point, we need to fetch again. This is the tricky part.

>  Another hook is sent before the previous check passes or fails (because of retries / someone quickly pushing an ammended commit because the first one was messed up) - We should cancel the first audit and its retries and try to fetch using the new sha/ref.

Why do we need to cancel the first audit? Wouldn't it be easier to just let if finish and set the status on the old commit?

> One thought, could git ls-remote origin refs/pull/77/head help us know if the remote is pointed at the right ref yet before we fetch it?

I think this would cause problems in the case of doubled up work. We shouldn't introduce any checks that rely on a specific like this because if there were quick successive updates, we may be checking for a SHA that will never be the HEAD on the remote. Making this change would require canceling previous requests, but at that point we've just added a lot of complexity for no actual gain, unless I'm missing something.

**Comment by dmethvin** [comment]
Just a sanity check here, did we check with GitHub to see what they said?

**Comment by scottgonzalez** [comment]
I've asked via their support form.

**Comment by scottgonzalez** [comment]
GitHub's response is basically that those are internal and "you shouldn't really be relying on them behaving in some specific way."

Guess we'll have to add remotes and fetch the original branches. Too bad they couldn't make that easier for us.
