### ISSUE TITLE
Show time of attempted verification

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#30]
From https://github.com/jquery/contribute.jquery.org/issues/110 by gibson042:

For technical reasons, we don't automatically recheck pull requests when a contributor signs the CLA. But pages/CLA/status.md doesn't provide enough information on its own to detect post-failure resolution, because it lacks the invocation time.

We should add text to the effect of "The following authors didn't have appropriate CLA signatures _as of [datetime]_", and also instructions to reactivate the checker by pushing a new commit to each affected pull request (perhaps suggesting `git commit --allow-empty -m '[CLA]: Recheck'`).

**Comment by gibson042** [comment]
Note that this is really only valuable if resolved quickly... as noted at https://github.com/jquery/contribute.jquery.org/issues/110#issuecomment-89777126 , jquery/jquery-license#6 is the long-term solution—this issue only exists to reduce noise and confusion in the interim.

**Comment by jzaefferer** [comment]
Now that #6 is resolved, this isn't needed anymore.
