### ISSUE TITLE
Auto-recheck failed PRs

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-license#6]
When we fetch updated CLA signatures, we can diff that against the previous list to find new signatures. If we then track which PRs failed because of which missing signatures, we can recheck PRs automatically.

**Comment by gnarf** [comment]
...or... we could trigger a new run whenever someone comments on a PR seems likey they'd come back and say "I signed this now"

**Comment by scottgonzalez** [comment]
That could result in a lot of checks though; some PRs have tons of comments.

**Comment by gnarf** [comment]
Maybe it only triggers a recheck if the status is failed?  Hopefully there aren't many comments on those.

**Comment by gnarf** [comment]
Also, does it store the datetime of the check currently?  That would be useful to know.

**Comment by gnarf** [comment]
and nevermind this whole idea about comments anyway, its likely to be immediate (which the update of signatures is not)

**Comment by rxaviers** [comment]
:+1: for this support given confusion on Globalize (e.g., https://github.com/jquery/globalize/pull/456)

**Comment by jzaefferer** [comment]
After reviewing the code with Scott: Should diff the signatures whenever they're updated. When there's new ones, iterate over failed PRs (store a reference in the prHook). If any new signature matches a failed PR, update that PR accordingly.

This partial refactoring might be useful: https://github.com/scottgonzalez/jquery-license/tree/signature-diff

**Comment by jzaefferer** [comment]
I've got a working test setup now. My plan (slightly updated from above) is to diff signatures to see if anything changed, then recheck previously failed PRs. I want to do the recheck by storing the payload for failed audits, then just running prHook again with the same payload. Reset the list before that, then have it fill again with anything that's still failing. Wouldn't survive a server restart, but that seems okay.

**Comment by rxaviers** [comment]
@jzaefferer, it's awesome this is fixed. A general question though: are existing PRs with failed CLA going to be rechecked (e.g., https://github.com/jquery/globalize/pull/456)?

**Comment by jzaefferer** [comment]
I mentioned this elsewhere, for completeness: No, only PRs that failed since the change was deployed, are rechecked. See #26 for manual checks.

**Comment by rxaviers** [comment]
Thanks
