### ISSUE TITLE
Make jquerybot allow greenkeeper.io PRs.

### ISSUE THREAD

**Issue by jdalton** [jquery/jquery-license#63]
Currently the @jquerybot will pop in on all @greenkeeperio-bot PRs.
There's an entry in the CLA excel for greenkeeper but that's not working. Can we make them get along?

**Comment by dmethvin** [comment]
Is the name and email for the bot in the CLA list correct? I added a name verification entry last night but it seems like it didn't help. Or maybe I'm misunderstanding the [code check here](https://github.com/jquery/jquery-license/blob/6c7a7b80cda6ff873ed17f84209e92404c2f4a16/lib/signatures.js#L62).

It may be a while but I think we'll have a (different) solution for this if we move to a DCO. That was something @kborchers was looking into.

**Comment by scottgonzalez** [comment]
It would help if the name were correct. I just changed it from "Greenkeeper" to "greenkeeperio-bot" which should fix it.

**Comment by jdalton** [comment]
:guitar: !
