### ISSUE TITLE
Only validate email on pull requests

### ISSUE THREAD

**Issue by nzakas** [jquery/jquery-license#69]
On ESLint, we are seeing a lot of issues with name mismatches and people having trouble configuring their git settings so it will work. At first glance, it seems like checking the author name is useless so long as the author email (a truly unique ID) is verified. 

Can we remove the name check and only validate the email address?

**Comment by dmethvin** [comment]
That is mainly a legal question so I'll let Kris weigh in. The logic behind having a real name as I understood it was that the person is the legal entity and an email address is not. I agree that it can be a speed bump for new contributors or when the project is joining and there is a backlog of previous contributors who have to sign.

**Comment by scottgonzalez** [comment]
We **just** had this discussion last week in #67 which had a lot of push back from project maintainers.

**Comment by dmethvin** [comment]
We still need input from legal and @kborchers to know if it's even possible.

**Comment by nzakas** [comment]
Just spit balling here: I understand the requirement to have a legal name on file somewhere. It just seems that if there's a spreadsheet that maps legal name to email, that checking the email attached to a commit should be enough. As long as you can retrieve the legal name later, that seems all that maintainers really need in a pinch (though I'm guessing that most are more familiar with GitHub usernames).

Interested to hear what legal has to say, but in the meantime, we are encountering a decent amount of issues related to this. Existing contributors are suffering through, but new ones are harder to convince to try re-pushing their PR with slight tweaks to their names.

**Comment by nzakas** [comment]
Here's another instance: https://github.com/eslint/eslint/pull/6018#issuecomment-216231484

In this case, note that we are getting an undesired effect: the user doesn't have his legal name configured in git so he signed the CLA with a nonlegal name.
